### ISSUE TITLE
Can I store a dictionary in memory accessed from each workers?

### ISSUE THREAD

**Issue by developez** [goriunov/ClusterWS#136]
### Submitting

- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other

### Details 

My server application has got two endpoints. One endpoint is the websocket connection and another endpoint is an UDP connection.

When a socket comes some data and the socket is stored in a dictionary in memory, I want to know if other workers executed in other cores (I suppose that ClusterWS execute each worker in a different core each time) can access to that dictionary in memory. In this is possible I think that the dictionary must me protected by mutex.

In other hand, when a udp connection comes, the process must access to that dictionary in memory and use the socket inside to emit things.

**Comment by goriunov** [comment]
I hope i understood correctly :)

Workers don't know about each other anything, so if you store socket in one worker another worker will not know about it. To communicate between workers you have to use `publishToWorkers` you can read more in [here](https://github.com/ClusterWS/ClusterWS/wiki/Middleware-Functions#communicate-between-workers-and-machines). With this stuff and Pub/Sub you should be able to write your own simple synchronisation logic if needed.

**Comment by developez** [comment]
Thank you, you understood good. Ok, I suppose that workers are created with fork(), so, like you say and according the documentation, each forked process has independent environment. Now I must think how deal with this, the problem that I have is this:

1. websocket receives one request message (from an app), for example: take an apple. The process put in the dictionary this pending action with an ID, the websocket is stored in the data estructure of the pending action that is stored in the dictionary.

2. Then in a second action, an udp packet is received with that ID by the UDP endpoint, in this process the pending action of that ID is retrieved and the websocket stored (step 1) is used to emit a message to the app.

This thing can be doing easily in one nodejs process, the problem is the scaling of this, by this reason I am reading of your solution, but I am stuck with the common accessed to the dictionary (may be there is a design mistake, but by the moment is the situation of the software developed).

**Comment by goriunov** [comment]
I see, one of the approaches will be to you Pub/Sub system.

For example WebSocket receives one request message "take an apple" with specific ID, then you simply subscribe that socket to that channel with that ID.

And whenever UDP endpoint receives data with the same ID you just publish to that channel. And if you don't want that socket to receive any more data just unsubscribe from the channel.

Pub/Sub is automatically distributed across all Workers. So if one socket on one worker connected  to the same channel as another socket in another worker they both will receive the same message.

**Comment by developez** [comment]
Good to read this, I think the same arquitecture and it seems that will scales good. Thank very much for your time.
