### ISSUE TITLE
Publish to channel but only to some users

### ISSUE THREAD

**Issue by caracal7** [goriunov/ClusterWS#138]
I need to make real-time changefeed like in the RethingDB.

I have a server-side collection and every document in this collection have a field like `['userid1','userid2','userid3','userid4']` with a list of users who have access to this document.

And for example, I have 1000 connected users who are looking to this collection and every user can see only a list of own documents. And then any document is changed I want to send the message only to users who can see the changed document. Not to everyone and this is why I can't use Pub/Sub.

I can use `socket.send()/socket.on()` for each user which I need but some connected users don't want to receive chengefeed right now and I don't have `socket.of()` at JavaScript client. Every connected user must subscribe and unsubscribe to changefeed at any time.

How can I solve this case?

**Comment by goriunov** [comment]
You can use pub sub for this task there are multiple ways to handle this problem with pub sub.

One of the approaches is to create separate channel for each document and then validate if user has access to that document on attempt to subscribe to that channel. When you publish to specific channel only the users who have been subscribed to that channel can get messages.

```js
// This code from ClusterWS 4 will look abit different in version 3
function worker() {
 ...
  wss.addMiddleware(Middleware.onSubscribe, (socket, channel, allow) => {
      // you can validate if this socket has access to that channel and the call
      // allow(true)   to allow subscription to that channel
      // allow(false) to restrict subscription
     
      // Just to note channel name can be any string
      // example we have document hello.txt and user have access
       if (channel === 'hello.txt') {
          return allow(true);
      }

     // example document new.txt user does not have access
      if(channel === 'new.txt') {
       return allow(false)
     }
   });
   
  // Then when document is modified you can do something like that
  // so only users who have been subscribed to that channel will receive message
 // with update
  wss.publish('hello.txt', 'what ever message you want to');


  wss.on('connection', (socket) => { ... })
}
```

**Comment by caracal7** [comment]
Thanks for fast response))

Hmm, I will try...

if I will make 10000 or more channels it is not a problem?

if I put a document id and user id into channel name it is not a problem for security?
For example

changefeed1@userid125
changefeed2@userid125
changefeed3@userid125
doc35change@userid125

But  I think it will be much easier if anybody can subscribe to one channel and I can send a message not only to every subscriber but also to specific socket connection only if this connection is subscribed.

**Comment by goriunov** [comment]
Creating 10000 channels should not be a problem. Second part is already working that way. When you publish message to channel it will automatically send message to every subscribed socket. You can subscribe as many users to as many channels you want (in reasonable numbers).  So you can call your channel `document1`  and subscribe 10 users to that channel. And when you publish it will automatically send message to all 10 assigned sockets (including on different instances).

There is no need to put user id in to channel name. Also socket will not know about what channels it should subscribe without passing verification on the server and sending back all allowed channels to user if he/she has access :) So there should not be any security issues. Also to do not expose actual document name you can use many different approaches for example hashing and salting of name or even generate temporary random names for specific channel and update it every once in a while.

I have attached more detailed example of subscribing to the documents. Please read comments :)
```js
function Worker() {
  ...
  const documentCollection = {
    "document1": ["user1", "user2", "user3"],
    "document2": ["user1"]
  }

  wss.addMiddleware(Middleware.onSubscribe, (socket, channel, allow) => {
    // if user2 tries to subscribe to document1 it will succeed 
    // and document2 will fail
    if(documentCollection[channel].includes(socket.name)) {
      return allow(true);
    }

    return allow(false); 
  });

  wss.on('connection', (socket, req) => {
    // do some verification of the user and find out who is it
    // we will assume it is user2
    socket.name = 'user2';
    
  })

  // whenever you publish update
  // it will automatically send message to all subscribed sockets
  wss.publish('document2', 'any data');
  ...
}
```

Just a note you can do user verification in `Middleware.verifyConnection`.

**Comment by goriunov** [comment]
It may be a bit confusing at the start, the best way is to try it out and see how it works :)

**Comment by caracal7** [comment]
I move this way
`

     wss.publish('mylogin1 doclist1', 'any data');
     wss.publish('mylogin2 doclist1', 'any data');
     wss.publish('mylogin3 doclist1', 'any data');
     wss.publish('mylogin3 anotherfeed', 'any data');
 
    ....

    wss.addMiddleware(Middleware.onSubscribe, (socket, channel, next) => {
        var x = channel.split(' ', 2);
        if(x.length === 2) {
            if(!socket.logged) next(false);
            if(socket.userLogin !== x[0]) return next(false);
        }
        next(true);
    })
`
Completly solve my issue
