### ISSUE TITLE
How to send msg by userid connection?

### ISSUE THREAD

**Issue by istoros** [goriunov/ClusterWS#141]
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other

How to send message to connection by userId?
I think, there is one decision:
1) Create array of clients on worker: `const users = [{userId, socket}, {userId, socket}, ...]` and push new clients in verifyMiddleware
2) If I want to send message by userId, I need: "publishToWorkers(userId, message)" => "onMessageFromWorker" witch `users.forEach(user => {if(userId == user.userId) { user.socket.send(message) }})`
Can I do it? And is there another solutions?

**Comment by goriunov** [comment]
@istoros sorry for little late reply, sure you can use above way or you can create separate channels for each user and just publish to that channel.
