### ISSUE TITLE
Don't understand what .processMessage is for?

### ISSUE THREAD

**Issue by rygo6** [goriunov/ClusterWS#148]
This is a nice lib so far, got it working. But this is still confusing me:

```
		// on message will intercept all events including system one
		// and will not process to the next step
		// (can be used to filter messages or implement own protocol and so on)
		socket.on('message', (msg: any) => {
			// to process to next step you have to call processMessage
			// process message accepts stringified array or just array
			// (based on ClusterWS protocol)
			socket.processMessage(msg);
		});
```

I don't understand the purpose of `socket.processMessage(msg);` or what is supposed to be happening there... ?

**Comment by goriunov** [comment]
Hey @rygo6 i am looking into working on new version of clusterws which may change some things. Basically clusterws supports default websocket communication with on message listener but to use clusterws features you have to provide specific commands to clusterws like `publish` event. 

So on message listener will get any type of messages from any client and then you have to transform that messages to clusterws complaint and push it in to the socket. (probably some work required in there)

**Comment by goriunov** [comment]
Here is example on how it should be looking, as new version of clusterws will strip lots of things which are just cumbersome

https://github.com/ClusterWS/ClusterWS/blob/next/examples/template.js#L53

**Comment by rygo6** [comment]
I see. So I assume this is used to send system messages right now of some kind? Could you explain more of that? Because I don't actually see system messages coming through.

**Comment by goriunov** [comment]
At that time plan was to add some system messages however i don't think that any were added. After some thoughts and experiments I have decided to create a new simpler template, here is initial draft on what ClusterWS will/may look like:

```js
const { ClusterWS } = require('../dist');

new ClusterWS({
  port: 3000,
  worker,
  scaleOptions: {
    workers: {
      instances: 100
    },
    brokers: {
      instances: 3,
      entries: [{ port: 3001 }, { port: 3002 }, { port: 3003 }]
    }
  },
  webSocketOptions: {
    // path: '/socket',
    engine: "ws", // make sure to install correct module
    // autoPing: true,
    // pingInterval: 20000,
    // appLevelPing: true // mostly used for browser will send ping in app level requires manual set up
  },
  // tlsOptions: { /** default node.js tls options */ }
})

async function worker() {
  const wss = this.server.wss;
  const server = this.server;
  const workerId = this.workerId;

  // send specific message to specific worker id
  server.sendToWorker("specific workerId", "My Message");

  // broadcast to all workers 
  server.broadcastToWorkers("My Message");


  wss.verifyClient((info, next) => {
    // verify and allow user to pass
    next(true);

    // fail user
    next(false);
  });

  wss.on('connection', (ws) => {
    console.log('New websocket connection');

    ws.on('message', (message) => {
      // handle on message

      // example of sending message
      ws.send("Send some message")
    });

    ws.on('error', (err) => {
      // handle on error
    });

    ws.on('pong', () => {
      // handle on pong received
    });

    ws.on('close', (code, reason) => {
      // handle on ws connection close
    });
  })

  server.on('messageFromWorker', (message) => {
    // other worker sent message
    // you can use this communicate between different clients on
    // different workers
  })

  server.on('error', (err) => {
    // includes websocket server errors
    console.log(`[${process.pid}] Server got an error: ${err}`);
  });

  server.start(() => {
    console.log(`[${process.pid}] Server is running`);
  });
}
```

Basically user will be responsible for communicating between different workers and detecting which worker holds necessary ws users (users discovery logic) by using `broadcastToWorkers` and then communicate with those brokers through `sendToWorker`. No more protocol messages between ws server and ws clients.

**Comment by rygo6** [comment]
I see, that is helpful to see. Thank you.

Can you provide an example of how to use the current pub/sub syntax? I am also a little confused about this. 

Like the subscribe and publish methods want an id, I assume I am supposed to get that from the pid, or other? Not just make a random one?

It looks like I subscribe with the WSServer.Subscribe to a channel, then the incoming messages get delivered to socket.on('message', callback)?

Then I see publish vs publishToWorkers. Is there any difference between using publishToWorkers and just subscribing all workers to the same channel?
